# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 涵月天-microzz.com
subtitle: IT技术分享
description: HTML/HTML5 CSS/CSS3 JavaScript React.js Vue.js Angular.js Node.js ES6 JS
keywords: JavaScript,ES6,Vue.js,React.js,Node.js,HTML5,CSS3,Angular.js,JS,HTML,CSS,前端,Web
author: Microzz
language: zh-Hans
timezone:
email: 903036377@qq.com

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://microzz.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: ['*.html','*.js','*.css',md/**,share/**,vue-chat/**,README.md,about/**,github-ranking/**,vue-music/**,vue-cnode/**]

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: indigo

feed:
  type: atom
  path: atom.xml
  limit: 0

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: true
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true

#baidu_url_submit:
#  count: 20 ## 比如3，代表提交最新的三个链接
#  host: microzz.com ## 在百度站长平台中注册的域名
#  token: SedJ4GFBP4jHVPUU ## 请注意这是您的秘钥， 请不要发布在公众仓库里!
#  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里

#deploy:

#   - type: git

#     repo: https://git.coding.net/microzz/hexo.git

#     branch: master

#   - type: baidu_url_submitter


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:microzz/microzz.github.io.git
  branch: master
