# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: 主页
    url: /
  archives:
    text: 文章
    url: https://microzz.com/archives/
  tags:
    text: 标签
    url: https://microzz.com/tags/
  #th-list:
  #  text: 分类
  #  url: /categories
  github:
    text: GitHub
    url: https://github.com/microzz
    target: _blank
  #user:
  #  text: 关于我
  #  url: https://microzz.com/about/
  pencil:
    text: 掘金专栏
    url: https://juejin.im/user/57f0f27a128fe100542d29ad
    target: _blank
  leaf:
    text: SegmentFault
    url: https://segmentfault.com/u/microzz/posts
    target: _blank
  leanpub:
    text: 垃圾分类学习
    url: https://garbage.microzz.com
  #music:
  #  text: Vue音乐播放器
  #  url: https://microzz.com/vue-music/
  #  target: _blank
  #comments:
  #  text: Vue CNode社区
  #  url: https://microzz.com/vue-cnode/
  #  target: _blank
  #globe:
  #  text: 智能聊天室
  #  url: https://microzz.com/vue-chat/
  #  target: _blank
  #star:
  #  text: GitHub排行榜
  #  url: https://microzz.com/github-ranking/
  #  target: _blank
  # link:
  #   text: 友链
  #   url: https://microzz.com/about/friendly.html

rss: /atom.xml

# 你的头像url
avatar: /static/avatar.png
# favicon
favicon: /favicon.ico

# email
email: zhaohui@microzz.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#3F51B5'

# 页面标题
tags_title: 标签
archives_title: 文章列表
categories_title: 分类

# 文章截断
excerpt_render: false
excerpt_length: 200
excerpt_link: 阅读全文...
mathjax: false
archive_yearly: true

# 是否显示文章最后更新时间
show_last_updated: true

# 是否开启分享
share: true

# 是否开启打赏，关闭 reward: false
reward:
  title: 请我吃辣条~
  wechat: /static/wechat.jpg     #微信，关闭设为 false
  alipay:  /static/alipay.jpg     #支付宝，关闭设为 false

# 是否开启搜索
search: true

# 是否大屏幕下文章页隐藏导航
hideMenu: true

# 是否开启toc
toc: false
#toc:
#  list_number: true  # 是否显示数字排序

# 文章页版权声明内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
copyright: 转载请注明出处：<a href="<%- url.replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- url.replace(/index\.html$/, '') %></a>

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# 百度统计，如要开启，改为你的 key
#baidu_tongji: ce268e8f61069a1636a4629acbb82b9a
baidu_tongji: false

# 腾讯分析，如要开启，输入站点id
tajs: false

# google
google_analytics: false
google_site_verification: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

# 是否开启多说评论，填写你在多说创建的站点二级域名
duoshuo: false
# 是否开启多说评论计数（该服务不稳定）
duoshuo_count: false
# 使用 disqus 时关闭多说评论
disqus_shortname: false


# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: false

# 版权起始年份
since_year: 2015

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: IT技术分享 涵月天-microzz.com

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: 站点总访客数：
  site_pv: 总访问量：
